title: Shishir Khanal
logo: /assets/img/001.jpg
description: Mechanical Engineer with a Master's Degree in AI
theme: minimal

# Social links
social_links:
  - name: LinkedIn
    url: https://jp.linkedin.com/in/er-shishir-khanal-26b125139
    icon: /assets/img/002.png

# Custom styles (if needed, or you can include them in a separate CSS file)
custom_css: |
  body {
      font-family: Arial, sans-serif;
      text-align: center;
      background-color: #f4f4f4;
  }
  .header {
      color: black;
      font-weight: bold;
  }
  .description {
      color: black;
      font-weight: bold;
      background-color: lightblue;
      padding: 10px;
      margin-top: 10px;
  }
  .linkedin-link {
      font-size: 16px;
      color: blue;
      text-decoration: none;
      display: inline-flex;
      align-items: center;
      font-weight: bold;
      position: relative;
      padding: 10px;
      margin: 10px;
      border-radius: 5px;
      transition: color 0.3s ease, transform 0.3s ease;
  }
  .linkedin-link:hover {
      color: darkblue;
      transform: scale(1.05);
  }
  .linkedin-link img {
      margin-right: 10px;
      width: 20px;
      height: 20px;
  }
